version: '3'

services:
   eapi_mongo:
     env_file: ./.env
     build:
       context: .
       dockerfile: Dockerfile.mongo
     image: mongodb
     ports:
       - 27017:27017
     volumes:
       - ./mongodb/data/db:/data/db
