version: '3.7'
services:
    # postgres:
    #     env_file: .env
    #     container_name: postgres
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./postgres
    #     ports:
    #         - 5432:5432
    # nginx:
    #     env_file: .env
    #     container_name: nginx
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./nginx
    #     restart: "no"
    #     ports:
    #         - 8000:80
    server:
        env_file: .env
        ports:
          - 5000:5000
        container_name: eapi_server
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - $PWD/server:/opt/server
        command: ["flask", "run", "-h", "0.0.0.0"]
