FROM python:3.6
EXPOSE 8000

RUN apt-get update -y --fix-missing
RUN apt-get install -y binutils libproj-dev gdal-bin psmisc

WORKDIR /opt/app
COPY . /opt/app/
ADD requirements.txt .
RUN pip install -r requirements.txt

CMD [ "bash" ]