# Generated by Django 2.0.3 on 2018-04-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsrer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precipevent',
            options={'verbose_name': 'Precip Events', 'verbose_name_plural': 'Precip Events'},
        ),
        migrations.AlterModelOptions(
            name='raingage',
            options={'verbose_name': 'Raingage', 'verbose_name_plural': 'Raingages'},
        ),
    ]
