"""Started building wgew preceip event model

Revision ID: 430a296fc4a4
Revises: baeffbb364d9
Create Date: 2021-04-23 17:23:15.609712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '430a296fc4a4'
down_revision = 'baeffbb364d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wgew_precipevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wgew_precipevent_id'), 'wgew_precipevent', ['id'], unique=False)
    op.create_table('wgew_raingage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wgew_raingage_id'), 'wgew_raingage', ['id'], unique=False)
    op.drop_index('ix_wgew_raingages_id', table_name='wgew_raingages')
    op.drop_table('wgew_raingages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wgew_raingages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wgew_raingages_pkey')
    )
    op.create_index('ix_wgew_raingages_id', 'wgew_raingages', ['id'], unique=False)
    op.drop_index(op.f('ix_wgew_raingage_id'), table_name='wgew_raingage')
    op.drop_table('wgew_raingage')
    op.drop_index(op.f('ix_wgew_precipevent_id'), table_name='wgew_precipevent')
    op.drop_table('wgew_precipevent')
    # ### end Alembic commands ###
