"""added raingage id to wgewraingage

Revision ID: 635c254da694
Revises: 96a6b7ef756f
Create Date: 2021-12-18 11:23:26.023037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635c254da694'
down_revision = '96a6b7ef756f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wgew_raingages', sa.Column('gage_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wgew_raingages', 'gage_id')
    # ### end Alembic commands ###
