"""added east to wgewraingage

Revision ID: 7202d0fceab8
Revises: 324ed4f5a03a
Create Date: 2021-12-18 09:29:56.244801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7202d0fceab8'
down_revision = '324ed4f5a03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wgew_raingages', sa.Column('east', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wgew_raingages', 'east')
    # ### end Alembic commands ###
