"""Initial schema setup

Revision ID: 86e274f40599
Revises: 
Create Date: 2021-12-21 12:46:37.410851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e274f40599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wgew_raingages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gage_id', sa.Integer(), nullable=True),
    sa.Column('watershed_id', sa.Integer(), nullable=True),
    sa.Column('east', sa.Integer(), nullable=True),
    sa.Column('north', sa.Integer(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('err', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wgew_raingages_gage_id'), 'wgew_raingages', ['gage_id'], unique=True)
    op.create_index(op.f('ix_wgew_raingages_id'), 'wgew_raingages', ['id'], unique=False)
    op.create_table('wgew_precip_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gage_id', sa.Integer(), nullable=True),
    sa.Column('watershed_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('time_est', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gage_id'], ['wgew_raingages.gage_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wgew_precip_events_id'), 'wgew_precip_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wgew_precip_events_id'), table_name='wgew_precip_events')
    op.drop_table('wgew_precip_events')
    op.drop_index(op.f('ix_wgew_raingages_id'), table_name='wgew_raingages')
    op.drop_index(op.f('ix_wgew_raingages_gage_id'), table_name='wgew_raingages')
    op.drop_table('wgew_raingages')
    # ### end Alembic commands ###
