"""Renamed wgew raingage table

Revision ID: 8ce9aadd174b
Revises: 9dbc23cd6cb0
Create Date: 2021-04-19 16:48:29.048281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce9aadd174b'
down_revision = '9dbc23cd6cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wgew_raingages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wgew_raingages_id'), 'wgew_raingages', ['id'], unique=False)
    op.drop_index('ix_raingages_id', table_name='raingages')
    op.drop_table('raingages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raingages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='raingages_pkey')
    )
    op.create_index('ix_raingages_id', 'raingages', ['id'], unique=False)
    op.drop_index(op.f('ix_wgew_raingages_id'), table_name='wgew_raingages')
    op.drop_table('wgew_raingages')
    # ### end Alembic commands ###
