"""added elev and err to wgewraingage

Revision ID: 96a6b7ef756f
Revises: 815fc4cf5518
Create Date: 2021-12-18 10:24:30.577870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a6b7ef756f'
down_revision = '815fc4cf5518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wgew_raingages', sa.Column('elevation', sa.Integer(), nullable=True))
    op.add_column('wgew_raingages', sa.Column('err', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wgew_raingages', 'err')
    op.drop_column('wgew_raingages', 'elevation')
    # ### end Alembic commands ###
