"""Added updated and created fields to raingage model

Revision ID: baeffbb364d9
Revises: 8ce9aadd174b
Create Date: 2021-04-21 10:51:41.571857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeffbb364d9'
down_revision = '8ce9aadd174b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wgew_raingages', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('wgew_raingages', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wgew_raingages', 'updated')
    op.drop_column('wgew_raingages', 'created')
    # ### end Alembic commands ###
