"""Started building wgew preceip event model

Revision ID: bc73a78818d6
Revises: 430a296fc4a4
Create Date: 2021-04-23 17:25:19.480058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc73a78818d6'
down_revision = '430a296fc4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
