"""created wgew_raingages table

Revision ID: db54d5173739
Revises: 
Create Date: 2021-12-20 13:12:43.157009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db54d5173739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wgew_raingages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gage_id', sa.Integer(), nullable=True),
    sa.Column('watershed_id', sa.Integer(), nullable=True),
    sa.Column('east', sa.Integer(), nullable=True),
    sa.Column('north', sa.Integer(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('err', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wgew_raingages_id'), 'wgew_raingages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wgew_raingages_id'), table_name='wgew_raingages')
    op.drop_table('wgew_raingages')
    # ### end Alembic commands ###
