version: '3'
services:
    eapidb:
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile.pgsql
        image: eapidb
        ports:
            - 5432:5432
        volumes:
            - ./db/pgdata:/var/lib/postgresql/data


#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgress
#      - POSTGRES_DB=postgres
