"""empty message

Revision ID: 234fdf965733
Revises: 89979cd57e4a
Create Date: 2018-03-24 20:13:46.401164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234fdf965733'
down_revision = '89979cd57e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('srer_raingages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('srer_raingages')
    # ### end Alembic commands ###
