name: test-action
on: [push]
jobs:
   show-message:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-python@v2
         - name: Run tests
         - run: pip install -r requirements.txt